version: "3.4"

services:
  dashboard:
    container_name: dashboard
    image: epayco:php-8.1
    ports:
      - "8000:80"
    volumes:
      - /home/jose/Proyectos/ePayco/dashboard-react/:/var/www/html/
    networks:
      - local

  manage2:
    container_name: manage2
    image: epayco:php-7.4
    ports:
      - "8001:80"
    volumes:
      - /home/jose/Proyectos/ePayco/manage2/:/var/www/html/
    networks:
      - local

  adquirencia:
    container_name: adquirencia
    image: epayco:php-8.1
    ports:
      - "8002:80"
    volumes:
      - /home/jose/Proyectos/ePayco/dashboard-react-adquirencia-movil/:/var/www/html/
    networks:
      - local

  panel-app-rest:
    container_name: panel-app-rest
    image: epayco:php-7.4
    ports:
      - "8003:80"
    volumes:
      - /home/jose/Proyectos/ePayco/panel_app_rest/:/var/www/html
      - ./config_ambiente_php7/files/001-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - local

  apify:
    container_name: apify
    image: epayco:php-8.1
    ports:
      - "8082:80"
    volumes:
      - /home/jose/Proyectos/ePayco/apify/rest_lumen/:/var/www/html/
    networks:
      - local

  conex:
    container_name: conex
    image: epayco:php-8.1
    ports:
      - "8083:80"
    volumes:
      - /home/jose/Proyectos/ePayco/apiservices/rest_lumen/:/var/www/html/
      - /var/www/html/rest_lumen/vendor
    networks:
      - local

  apify-private:
    container_name: apify-private
    image: epayco:php-7.4
    ports:
      - "8084:80"
    volumes:
      - /home/jose/Proyectos/ePayco/apify-private/:/var/www/html/
    networks:
      - local

  rest-private:
    container_name: rest-private
    image: epayco:php-7.4
    ports:
      - "8087:80"
    volumes:
      - /home/jose/Proyectos/ePayco/rest_private/:/var/www/html/public
    networks:
      - local

  rest-pagos:
    container_name: rest-pagos
    image: epayco:php-8.1
    ports:
      - "8089:80"
    volumes:
      - /home/jose/Proyectos/ePayco/epayco-rest/:/var/www/html/
    networks:
      - local

  ms-withdrawals:
    container_name: ms-withdrawals
    image: epayco:php-8.1
    working_dir: /var/www/html
    ports:
      - "8090:80"
    volumes:
      - /home/jose/Proyectos/ePayco/ms-withdrawals/:/var/www/html
    networks:
      - local

networks:
  local:
    name: local

# docker compose up -d